apiVersion: v2
name: mysqldump
description: git backup
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/mariadb/server/tree/10.5/client
type: application
version: 0.1.15
appVersion: "11.4.9-r0"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
