apiVersion: v2
name: mariadb-galera
description: MariaDB with Galera clustering
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/MariaDB/server
- https://github.com/MariaDB/galera
type: application
version: 0.1.0
appVersion: "10.4.20"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
