apiVersion: v2
name: mariadb-galera
description: MariaDB with Galera clustering
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/MariaDB/server
- https://github.com/MariaDB/galera
type: application
version: 0.1.1
appVersion: "12.0.2"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
