version: "3"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/udp-nginx-proxy:latest
    image: udp-nginx-proxy
    environment:
      BACKENDS: ${UDP_BACKENDS:-self}
      PORT_BACKEND: ${PORT_UDPPROXY_BACKEND:-53}
    ports:
    - 53:53/udp
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
      replicas: 2

networks:
  default:
    external:
      name: app_net
