apiVersion: v2
name: rainloop
description: Rainloop webmail server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/RainLoop/rainloop-webmail
type: application
version: 0.1.0
appVersion: "1.13.0"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
