apiVersion: v2
name: artifactory
description: JFrog Artifactory service
type: application
version: 0.1.1
appVersion: "6.15.1"
dependencies:
- name: chartlib
  version: 0.1.1
  repository: https://instantlinux.github.io/docker-tools
