---
# lirc-ubuntu.yml
#  IR remote device configuration for ubuntu

- name: LIRC config for device
  template:
    dest: /etc/lirc/{{ ir_device.module }}.conf
    src: lircd.conf.j2

- name: Set symlink to device file
  file:
    dest: /etc/lirc/lircd.conf
    force: yes
    src: /etc/lirc/{{ ir_device.module }}.conf
    state: link    

- name: LIRC startup
  template:
    dest: /etc/lirc/lircrc
    src: lircrc.j2

- name: Set up xorg.conf.d
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: Disable evdev processing for IR device in X11
  template:
    dest: /etc/X11/xorg.conf.d/10-lirc-disable.conf
    src: 10-lirc-disable.conf.j2

- name: Enable LIRCD
  lineinfile:
    dest: /etc/lirc/hardware.conf
    line: START_LIRCD="true"
    regexp: "^START_LIRCD=.*"

- name: Specify IR device name
  lineinfile:
    dest: /etc/lirc/hardware.conf
    line: REMOTE_DEVICE="{{ ir_device.device }}"
    regexp: "^REMOTE_DEVICE=.*"

- name: Specify IR config name
  lineinfile:
    dest: /etc/lirc/hardware.conf
    line: REMOTE_LIRCD_CONF="/etc/lirc/{{ ir_device.module }}.conf"
    regexp: "^REMOTE_LIRCD_CONF=.*"

- name: Enable lirc
  service:
    name: "{{ ir_device.service_name }}"
    enabled: yes
