---
# packages-ubuntu.yml

- name: Add the mythtv repo
  ansible.builtin.apt_repository:
    repo: ppa:mythbuntu/{{ mythtv_version }}

- name: Import repository keys for additional repos
  apt_key:
    id: "{{ item.value }}"
    keyserver: keyserver.ubuntu.com
  with_dict: "{{ ubuntu_apt_keys }}"

- name: Ensure repositories available
  apt_repository:
    repo: "{{ item }}"
    filename: ubuntu
  with_items: "{{ ubuntu_repos }}"

- name: Update repository sources
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install system packages
  apt:
    name: "{{ ubuntu_packages }}"

- name: Remove akonadi-dependent packages
  apt:
    autoremove: yes
    name:
    - akonadi-server
    - kaddressbook
    - kmail
    - korganizer
    state: absent

- name: Enable dvdcss
  environment:
    DEBIAN_FRONTEND: noninteractive
  command: dpkg-reconfigure libdvd-pkg
  args:
    creates: /usr/lib/x86_64-linux-gnu/libdvdcss.so
  when: ansible_distribution_version >= '18.04'
