apiVersion: v2
name: ddclient
description: Dynamic-DNS client
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/ddclient/ddclient/
type: application
version: 0.1.1
appVersion: "3.9.1-r1"
dependencies:
- name: chartlib
  version: 0.1.5
  repository: https://instantlinux.github.io/docker-tools
