---
# desktop-ubuntu.yml
#  Desktop configuration for Ubuntu

- name: Start X11 at boot time
  file:
    path: /etc/systemd/system/default.target
    src: /lib/systemd/system/graphical.target
    state: link
   
- name: Autologin after boot
  template:
    dest: /etc/lightdm/lightdm.conf.d/10-autologin.conf
    src: lightdm-autologin.conf.j2

- name: KDE config directories
  file:
    owner: mythtv
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
  - /home/mythtv/.config
  - /home/mythtv/.config/autostart
  - /home/mythtv/.config/autostart-scripts

- name: Disable screen lock
  template:
    dest: /home/mythtv/.config/kscreenlockerrc
    src: kscreenlockerrc.j2

- name: Disable energy-saver
  template:
    dest: /home/mythtv/.config/powermanagementprofilesrc
    src: powermanagementprofilesrc.j2

- name: Add autostart script for IR and X config
  file:
    path: /home/mythtv/.config/autostart-scripts/setup.sh
    src: /home/mythtv/setup.sh
    state: link

- name: Autostart MythTV frontend
  template:
    dest: /home/mythtv/.config/autostart/mythtv.desktop
    src: mythtv.desktop.j2

# TODO: ancillary things still need manual configuration
#  add MythTV and Chrome to launcher bar
#  audio config
