version: "3.2"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/rsyslogd:${VERSION_RSYSLOGD:-latest}
    environment:
      TZ: ${TZ:-UTC}
    hostname: rsyslogd.docker
    volumes:
    - ${ADMIN_PATH:-/opt}/rsyslogd/etc/logrotate.d:/etc/logrotate.d:ro
    - ${ADMIN_PATH:-/opt}/rsyslogd/etc/rsyslog.d:/etc/rsyslog.d:ro
    - logs:/var/log
    ports:
    - ${PORT_RSYSLOGD:-514}:514

volumes:
  logs:
networks:
  default:
    external:
      name: app_net
