version: "3"
services:

  app:
    image: nginx:${VERSION_NGINX:-latest}
    command: >
      sh -c "apk add --update --no-cache openssh rsync &&
      ssh-keygen -A && /usr/sbin/sshd &&
      adduser -u 2060 -s /bin/sh -g Weather -D wx &&
      passwd -u wx &&
      mkdir -p ${WX_RSYNC_DEST:-/var/wx} &&
      chown wx ${WX_RSYNC_DEST:-/var/wx} &&
      mkdir -m 700 /home/wx/.ssh &&
      cp /run/id_rsa.pub /home/wx/.ssh/authorized_keys &&
      chown -R wx /home/wx/.ssh &&
      exec /usr/sbin/nginx -g 'daemon off;'"
    ports:
    - ${PORT_WX_SSH:-2222}:22
    - ${PORT_WX_HTTP:-80}:80
    volumes:
    - ${ADMIN_PATH:-/opt}/wx/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    - ${ADMIN_PATH}/wx/ssh/id_rsa.pub:/run/id_rsa.pub:ro
    - ${SHARE_PATH}/wx-nginx/etc/ssh:/etc/ssh
    - html:${WX_RSYNC_DEST-/var/wx}
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

volumes:
  html:
networks:
  default:
    external:
      name: app_net
