version: "3.1"

services:

  app:
    image: ${REGISTRY_URI:-instantlinux}/ez-ipupdate:${VERSION_:-latest}
    environment:
      HOST: ${DYNAMIC_HOSTNAME:-www.mydomain.com}
    secrets:
    - ez-ipupdate-user

networks:
  default:
    external:
      name: app_net
secrets:
  ez-ipupdate-user:
    external: true
