version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/git-dump:${VERSION_GITDUMP:-latest}
    hostname: git-dump
    environment:
      TZ: ${TZ:-UTC}
      REPO_PREFIX: git@git.${MYDOMAIN}:richb/
      API_TOKEN_SECRET: git.${MYDOMAIN}-api-token
      SSH_PORT: ${PORT_GITLAB_SSH:-22}
    volumes:
    - backup:/var/backup
    - logs:/var/log
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary
    secrets:
    - source: git-dump_sshkey
      mode: 0400
    - source: git.${MYDOMAIN}-api-token
      gid: '505'
      mode: 0440
    
volumes:
  logs:
  backup:
    external: true
networks:
  default:
    external:
      name: app_net
secrets:
  git-dump_sshkey:
    external: true
  git.instantlinux.net-api-token:
    external: true
