# Usage:
#  Create a secret redis-config with an entry for a redis password:
#    apiVersion: v1
#    data:
#      redis.conf: |
#        requirepass abcdef1234
#    kind: Secret
#    metadata:
#      name: redis-config
#    type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
  ports:
  - port: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: $SERVICE_NAME
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        image: clems4ever/authelia:$VERSION_AUTHELIA
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/authelia/config.yml
          name: config
          readOnly: true
          subPath: config.yml
        - mountPath: /var/lib/authelia/store
          name: share
          subPath: $SERVICE_NAME/store
      dnsConfig:
        options:
        - name: use-vc
        - name: ndots
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: config
        secret:
          secretName: authelia-config
      - name: share
        hostPath: { path: $PATH_SHR }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: authelia-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: authtotp.$DOMAIN
    hosts:
    - authtotp.$DOMAIN
  rules:
  - host: authtotp.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ldap
  name: ldap
spec:
  # TODO remove fixed IP address once coredns issues are fixed
  clusterIP: $LDAP_IP
  ports:
  - port: 389
  selector:
    app.kubernetes.io/name: ldap
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ldap
  name: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ldap
    spec:
      containers:
      - name: ldap
        env:
        - { name: SLAPD_ORGANISATION, value: Community Internet }
        - { name: SLAPD_DOMAIN, value: $DOMAIN }
        - { name: SLAPD_PASSWORD, value: password }
        - { name: SLAPD_ADDITIONAL_MODULES, value: memberof }
        - { name: SLAPD_ADDITIONAL_SCHEMAS, value: openldap }
        - { name: SLAPD_FORCE_RECONFIGURE, value: "true" }
        image: dinkel/openldap:latest
        ports:
        - containerPort: 389
        volumeMounts:
        - mountPath: /etc/ldap.dist/prepopulate
          name: admin
          readOnly: true
          subPath: services/$SERVICE_NAME/ldap
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  # TODO remove fixed IP address once kubedns issues are fixed
  clusterIP: $REDIS_IP
  selector:
    app.kubernetes.io/name: redis
  ports:
  - port: 6379
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - name: redis
        command: [redis-server]
        args: [/etc/redis/redis.conf]
        image: redis:3.2.11-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /etc/redis/redis.conf
          name: redis-config
          readOnly: true
          subPath: redis.conf
      volumes:
      - name: redis-config
        secret:
          secretName: redis-config
