---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: TZ, value: $TZ }
        image: nextcloud:$VERSION_NEXTCLOUD
        command: [/bin/bash]
        args:
        - -c
        - >
          set -x &&
          usermod -a -G users www-data &&
          exec apache2-foreground
        resources:
          limits:
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 768Mi
        volumeMounts:
        - mountPath: /var/www/html
          name: synced
          subPath: html
        - mountPath: /pictures
          name: pictures
        # TODO: figure out a better way to handle NextCloud's upside-
        #  down naming hierarchy. If your photo collection has the year
        #  at a high level of the hierarchy, there's a conflict.
        - mountPath: /var/www/html/data/$CLOUD_USER1/files/Photos/2018
          name: pictures
          subPath: DigitalPics/2018/$CLOUD_USER1-nextcloud
        - mountPath: /var/www/html/data/$CLOUD_USER1/files/Photos/2019
          name: pictures
          subPath: DigitalPics/2019/$CLOUD_USER1-nextcloud
        - mountPath: /var/www/html/data/$CLOUD_USER2/files/Photos/2018
          name: pictures
          subPath: DigitalPics/2018/$CLOUD_USER2-nextcloud
        - mountPath: /var/www/html/data/$CLOUD_USER2/files/Photos/2019
          name: pictures
          subPath: DigitalPics/2019/$CLOUD_USER2-nextcloud
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: synced
        hostPath: { path: $K8S_VOLUMES_PATH/$SERVICE_NAME }
      - name: pictures
        persistentVolumeClaim:
          claimName: pictures
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1280M
    nginx.ingress.kubernetes.io/proxy-body-size: 1280M
    nginx.ingress.kubernetes.io/configuration-snippet: |
      fastcgi_buffers 32 32K;
      fastcgi_buffer_size 32K;
      fastcgi_max_temp_file_size 0;
      fastcgi_read_timeout 240;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-totp
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$AUTHELIA_IP/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://authtotp.$DOMAIN
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /index.php/login
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
