---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: $ETCD_IP
  ports:
  - port: 2379
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
    release: "0.1"
  name: $SERVICE_NAME
spec:
  replicas: $ETCD_NUM_NODES
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
      release: "0.1"
  serviceName: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
        release: "0.1"
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - name: DISCOVERY_TOKEN
          valueFrom:
            secretKeyRef:
              key: etcd-token
              name: etcd-token
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # TODO use pod DNS name when coredns working reliably
        #  (this requires running with hostNetwork: true)
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - { name: ETCD_ADVERTISE_CLIENT_URLS,
            value: "http://$(NODENAME):2379" }
        - { name: ETCD_DATA_DIR, value: /var/lib/etcd }
        - { name: ETCD_INITIAL_ADVERTISE_PEER_URLS,
            value: "http://$(NODENAME):2380" }
        - { name: ETCD_LISTEN_CLIENT_URLS, value: "http://0.0.0.0:2379" }
        - { name: ETCD_LISTEN_PEER_URLS, value: "http://0.0.0.0:2380" }
        image: quay.io/coreos/etcd:$VERSION_ETCD
        command: [/bin/sh]
        args:
        - -c
        - >
          echo "$DISCOVERY_IP discovery.etcd.io" >> /etc/hosts &&
          apk add --update ca-certificates &&
          /usr/local/bin/etcd \
            -discovery https://discovery.etcd.io/$(DISCOVERY_TOKEN)
        ports:
        - containerPort: 2379
        - containerPort: 2380
        volumeMounts:
        - mountPath: /var/lib/etcd
          name: data
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
      hostNetwork: true
      serviceAccountName: $K8S_NAMESPACE-privileged
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 50Mi
