---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - { port: 80, targetPort: 8080 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
spec:
  ports:
  - port: 4822
  selector:
    app.kubernetes.io/name: guacd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: GUACD_HOSTNAME, value: $(GUACD_SERVICE_HOST) }
        - { name: GUACD_PORT, value: $(GUACD_SERVICE_PORT) }
        - { name: MYSQL_DATABASE, value: guacamole }
        - { name: MYSQL_HOSTNAME, value: $DB_HOST }
        - { name: MYSQL_PASSWORD, value: $GUACAMOLE_DBPASS }
        - { name: MYSQL_USER, value: guacamole_user }
        image: guacamole/guacamole:$VERSION_GUACAMOLE
        ports:
        - containerPort: 8080
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: guacd
  name: guacd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacd
    spec:
      hostname: guacd
      subdomain: $SERVICE_NAME
      containers:
      - name: guacd
        image: guacamole/guacd:$VERSION_GUACAMOLE
        ports:
        - containerPort: 4822
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guacamole-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /guacamole
    nginx.ingress.kubernetes.io/proxy-buffering: off
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  rules:
  - host: desktop.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
  tls:
  - hosts:
    - desktop.$DOMAIN
    secretName: desktop.$DOMAIN
#   secretName: letsencrypt-certs
