---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - { port: 80, targetPort: 8080 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
spec:
  ports:
  - port: 4822
  selector:
    app.kubernetes.io/name: guacd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: GUACD_HOSTNAME, value: $(GUACD_SERVICE_HOST) }
        - { name: GUACD_PORT, value: $(GUACD_SERVICE_PORT) }
        - { name: MYSQL_DATABASE, value: guacamole }
        - { name: MYSQL_HOSTNAME, value: $DB_HOST }
        - { name: MYSQL_USER, value: guacamole_user }
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: guacamole-db-password
              key: guacamole-db-password
        image: guacamole/guacamole:$VERSION_GUACAMOLE
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 768Mi
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: guacd
  name: guacd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacd
    spec:
      hostname: guacd
      subdomain: $SERVICE_NAME
      containers:
      - name: guacd
        image: guacamole/guacd:$VERSION_GUACAMOLE
        ports:
        - containerPort: 4822
        resources:
          limits:
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 32Mi
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guacamole-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /guacamole
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  rules:
  - host: desktop.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
  tls:
  - hosts:
    - desktop.$DOMAIN
    secretName: tls-$SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-totp
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$AUTHELIA_IP/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://authtotp.$DOMAIN
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - desktop.$DOMAIN
  rules:
  - host: desktop.$DOMAIN
    http:
      paths:
      - path: /guacamole/\#/login
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
