# This is an example where https://monitor.$domain is hosted outside
#  kubernetes, on pair of vhosts serving a monitoring dashboard at
#  $PORT_NAGIOSQL and nagios at port 80.
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  externalName: $MONITOR_IP
  type: ExternalName
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    # TODO - letsencrypt (can't deal with these redirects and basic-auth)
    #  Doesn't validate when using type ExternalName
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: $SERVICE_NAME.$DOMAIN
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /nagios
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: $PORT_NAGIOSQL
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-totp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$AUTHELIA_IP/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://authtotp.$DOMAIN
spec:
  tls:
  - secretName: $SERVICE_NAME.$DOMAIN
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /NagiosQL/index.php
        backend:
          serviceName: $SERVICE_NAME
          servicePort: $PORT_NAGIOSQL
