---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  ports:
  - { port: 80, targetPort: 8081, name: $SERVICE_NAME }
  - { port: $PORT_NEXUS_REGISTRY, targetPort: 5000, name: registry }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: -Xms1536m -Xmx2048m -XX:MaxDirectMemorySize=3g
        - { name: TZ, value: $TZ }
        image: sonatype/nexus3:$VERSION_NEXUS
        ports:
        - containerPort: 5000
        - containerPort: 8081
        resources:
          limits:
            memory: 6144Mi
          requests:
            cpu: 200m
            memory: 1280Mi
        volumeMounts:
        - mountPath: /nexus-data
          name: $SERVICE_NAME
      nodeSelector:
        service.$SERVICE_NAME: allow
      volumes:
      - name: $SERVICE_NAME
        hostPath: { path: $K8S_VOLUMES_PATH/$SERVICE_NAME }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if (${DOL}http_user_agent ~ docker ) {
        # proxy_pass http://$K8S_NAMESPACE-$SERVICE_NAME-$PORT_NEXUS_REGISTRY;
        proxy_pass http://$SERVICE_NAME.$K8S_NAMESPACE:$PORT_NEXUS_REGISTRY;
      }
spec:
  tls:
  - secretName: $SERVICE_NAME.$MYDOMAIN
    hosts:
    - $SERVICE_NAME.$MYDOMAIN
  rules:
  - host: $SERVICE_NAME.$MYDOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: $PORT_NEXUS_REGISTRY
