---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: $WX_NGINX_IP
  ports:
  - { port: $PORT_WX_SSH, targetPort: 22, name: ssh }
  - { port: 80, targetPort: 80, name: $SERVICE_NAME }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        command: [/bin/sh]
        args:
        - -c
        - >
          apk add --update --no-cache openssh rsync &&
          ssh-keygen -A && /usr/sbin/sshd &&
          adduser -u 2060 -s /bin/sh -g Weather -D wx &&
          passwd -u wx &&
          mkdir -p $WX_RSYNC_DEST &&
          chown wx $WX_RSYNC_DEST &&
          mkdir -m 700 /home/wx/.ssh &&
          cp /run/id_rsa.pub /home/wx/.ssh/authorized_keys &&
          chown -R wx /home/wx/.ssh &&
          exec /usr/sbin/nginx -g 'daemon off;'
        image: nginx:$VERSION_NGINX
        ports:
        - containerPort: 22
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: admin
          readOnly: true
          subPath: services/wx/etc/nginx/conf.d
        - mountPath: /run/id_rsa.pub
          name: admin
          subPath: services/wx/ssh/id_rsa.pub
          readOnly: true
        - mountPath: /etc/ssh
          name: share
          subPath: $SERVICE_NAME/etc/ssh
        - mountPath: $WX_RSYNC_DEST
          name: html
      dnsConfig:
        options: [ name: ndots ]
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: html
        emptyDir: { medium: Memory, sizeLimit: 50Mi }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: wx.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
