version: "3"
services:

  app:
    image: ${REGISTRY_URI:-instantlinux}/dropbox:${VERSION_DROPBOX:-latest}
    hostname: dropbox-docker
    environment:
      UID: ${DROPBOX_UID:-1000}
    ports:
    - ${PORT_DROPBOX:-17500}:17500
    volumes:
    - ${DROPBOX_PATH}:/home/user/Dropbox
    - ${SHARE_PATH}/dropbox/state:/home/user/.dropbox
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

networks:
  default:
    external:
      name: app_net
