apiVersion: v2
name: samba-dc
description: Samba domain controller
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- ttps://gitlab.com/samba-team/samba
type: application
version: 0.1.7
appVersion: "4.16.7-r0"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
