version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/mysqldump:latest
    environment:
      TZ: ${TZ:-UTC}
      SERVERS: ${DB_HOST:-db}
    volumes:
    - backup:/var/backup
    - logs:/var/log
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary
    secrets:
    - mysql-backup

volumes:
  logs:
  backup:
    external: true
networks:
  default:
    external:
      name: dbcluster
secrets:
  mysql-backup:
    external: true
