apiVersion: v2
name: davite
description: David Madison's event invitation service
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/instantlinux/docker-tools/tree/master/images/davite/src
type: application
version: 0.1.0
appVersion: "19.06"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
