apiVersion: v2
name: alertmanager
description: Prometheus alerting
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://hub.docker.com/r/prom/alertmanager
type: application
version: 0.1.1
appVersion: "v0.30.1"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
