apiVersion: v2
name: ez-ipupdate
description: Dynamic-DNS client
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://sourceforge.net/projects/ez-ipupdate/
type: application
version: 0.1.1
appVersion: "3.0.10-r9"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
