apiVersion: v2
name: blacklist
description: DNS blacklist for spamassassin
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/spamhaus/rbldnsd
type: application
version: 0.1.5
appVersion: "1.0"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
