apiVersion: v2
name: weewx
description: Weather Station software
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/weewx/weewx/
type: application
version: 0.1.5
appVersion: "4.10.2"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
