apiVersion: v2
name: weewx
description: Weather Station software
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/weewx/weewx/
type: application
version: 0.1.2
appVersion: "4.5.1"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
