version: "3"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/davite:${VERSION_DAVITE:-latest}
    environment:
      HOSTNAME: davite.${DOMAIN}
      SMTP_PORT: '25'
      SMTP_SMARTHOST: smtp.${DOMAIN}
      TCP_PORT: ''
    volumes:
    - ${SHARE_PATH}/davite:/var/adm/DaVite_Data
    ports:
    - ${PORT_DAVITE:-8080}:80
    hostname: davite.${DOMAIN}
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

networks:
  default:
    external:
      name: app_net
