apiVersion: v2
name: proftpd
description: FTP server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/proftpd/proftpd
type: application
version: 0.1.1
appVersion: "1.3.7a-r0"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
