apiVersion: v2
name: rsyslogd
description: rsyslogd
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/rsyslog/rsyslog
type: application
version: 0.1.14
appVersion: "8.2512.0-r0"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
