apiVersion: v2
name: haproxy-keepalived
description: Load balancer with haproxy and keepalived
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/haproxy/haproxy
- https://github.com/acassen/keepalived
type: application
version: 0.1.8
appVersion: "2.6.6-alpine-2.2.7-r1"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: http://instantlinux.github.io/docker-tools
