apiVersion: v2
name: haproxy-keepalived
description: Load balancer with haproxy and keepalived
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/haproxy/haproxy
- https://github.com/acassen/keepalived
type: application
version: 0.1.2
appVersion: "2.4.1-alpine-2.2.1-r0"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
