apiVersion: v2
name: restic
description: Restic backups
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/restic/restic
type: application
version: 0.1.8
# Remember to update restic==<ver> in values.yaml as releases are published;
#  the values.yaml file is not able to reference .Chart.appVersion
appVersion: "0.16.2-r1"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
