apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local.fullname" . }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "{{ .Values.homeserver_url }}",
                "server_name": "{{ .Values.server_name }}"
            },
            "m.identity_server": {
                "base_url": "https://vector.im"
            }
        },
        "disable_custom_urls": false,
        "disable_guests": false,
        "disable_login_language_selector": false,
        "disable_3pid_login": false,
        "brand": "Element",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "integrations_widgets_urls": [
                "https://scalar.vector.im/_matrix/integrations/v1",
                "https://scalar.vector.im/api",
                "https://scalar-staging.vector.im/_matrix/integrations/v1",
                "https://scalar-staging.vector.im/api",
                "https://scalar-staging.riot.im/scalar/api"
        ],
        "bug_report_endpoint_url": "https://element.io/bugreports/submit",
        "defaultCountryCode": "{{ .Values.country_code }}",
        "show_labs_settings": false,
        "features": {
            "feature_video_rooms": false,
            "feature_new_room_decoration_ui": true,
            "feature_group_calls": false,
            "feature_element_call_video_rooms": false,
            "feature_use_device_session_member_events": true
        },
        "default_federate": true,
        "default_theme": "light",
        "room_directory": {
            "servers": {{ .Values.room_directory_servers }}
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false,
            "https://matrix-client.matrix.org": false
        },
        "setting_defaults": {
            "breadcrumbs": true
        },
        "jitsi": {
            "preferred_domain": "meet.element.io"
        },
        "element_call": {
            "url": "{{ .Values.call.widget_url }}",
            "participant_limit": 8,
            "brand": "Element Call",
            "use_exclusively": true
        }
    }
  client: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "{{ .Values.homeserver_url }}",
                "server_name": "{{ .Values.server_name }}"
            },
            "m.identity_server": {
                "base_url": "https://vector.im"
            }
        },
        "org.matrix.msc4143.rtc_foci": [{
            "type": "livekit",
            "livekit_service_url": "{{ .Values.call.livekit_service_url }}"
        }]
    }
  element.json: |
    {"call": {"widget_url": "{{ .Values.call.widget_url }}" }}
