apiVersion: v2
name: mt-daapd
description: Dynamic-DNS client
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://sourceforge.net/projects/mt-daapd/
type: application
version: 0.1.2
appVersion: "26.4-dfsg1-1"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
