apiVersion: v2
name: owntone
description: iTunes / Roku-compatible media server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/owntone/owntone-server
type: application
version: 0.1.0
appVersion: "29.0"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
