apiVersion: v2
name: wordpress
description: WordPress content management
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://build.trac.wordpress.org/browser
type: application
version: 0.1.0
appVersion: "5.7.1-php7.4-apache"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
