version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/samba-dc:latest
    restart: always
    network_mode: host
    hostname: ${SAMBADC_HOSTNAME:-dc.example.com}
    environment:
      DOMAIN_ACTION: join
      INTERFACES: ${SAMBADC_INTERFACES:-lo eth0}
      REALM: ${SAMBA_REALM:-ad.example.com}
      TZ: ${TZ:-UTC}
      WORKGROUP: ${SAMBA_WORKGROUP:-WORKGROUP}
    volumes:
      - etc:/etc/samba
      - lib:/var/lib/samba
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 3268-3269:3268-3269
      - 49152-65535
    secrets:
      - samba-admin-password

volumes:
  etc:
  lib:
secrets:
  samba-admin-password:
    file: /var/adm/admin/secrets/samba-admin-password
