version: "3.1"

services:

  dovecot:
    image: ${REGISTRY_URI:-instantlinux}/dovecot:${VERSION_DOVECOT:-latest}
    volumes:
    - ${ADMIN_PATH:-/opt}/dovecot/etc/:/etc/dovecot/conf.local:ro
    - ${ADMIN_PATH:-/opt}/dovecot/postfix/etc/:/etc/postfix/postfix.d:ro
    - ${SHARE_PATH}/common/pki/certs:/etc/ssl/certs:ro
    - inbox:/var/spool/mail
    - spool:/var/spool/postfix
    - webmail:/home
    ports:
    - ${PORT_DOVECOT_SMTP:-25}:25
    - ${PORT_DOVECOT_IMAPD:-143}:143
    - ${PORT_DOVECOT_IMAPS:-993}:993
    secrets:
    - ldap-ro-password
    - postfix-sasl-passwd
    - webmail.ci.net-server-key.pem 
    deploy:
      placement:
        constraints:
        - node.labels.mail-sync-member == true
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 10

  syncprimary:
    image: ${REGISTRY_URI:-instantlinux}/swarm-sync:latest
    environment:
      SYNC_INTERVAL: "2"
    volumes:
    - syncarchive:/root/.unison
    - synclogs:/var/log/unison
    - webmail:/var/swarm-sync/webmail
    - inbox:/var/swarm-sync/inbox
    secrets:
    - swarm-sync_sshkey
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary
    depends_on:
    - peer

  peer:
    image: ${REGISTRY_URI:-instantlinux}/swarm-sync:latest
    environment:
      SYNC_ROLE: peer
    env_file:
    - ../../.docker/swarm-sync.pub.env
    volumes:
    - etcssh:/etc/ssh
    - inbox:/var/swarm-sync/inbox
    - syncarchive:/root/.unison
    - webmail:/var/swarm-sync/webmail
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == peer

volumes:
  etcssh:
  inbox:
  spool:
  synclogs:
  syncarchive:
  webmail:
networks:
  default:
    external:
      name: app_net
secrets:
  ldap-ro-password:
    external: true
  postfix-sasl-passwd:
    external: true
  swarm-sync_sshkey:
    external: true
  webmail.ci.net-server-key.pem:
    external: true
