apiVersion: v2
name: prometheus
description: Prometheus metrics and alerting
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://hub.docker.com/r/prom/prometheus
type: application
version: 0.1.3
appVersion: "v3.9.1"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
