---
# lirc.yml
#  IR remote device configuration

- name: Create /etc/lirc path
  file:
    path: /etc/lirc
    state: directory

- name: LIRC config
  template:
    dest: /etc/lirc/lircd.conf
    src: lircd.conf.j2

- name: LIRC startup
  template:
    dest: /etc/lirc/lircrc
    src: lircrc.j2

- name: Disable evdev processing for IR device in X11
  template:
    dest: /etc/X11/xorg.conf.d/10-lirc-disable.conf
    src: 10-lirc-disable.conf.j2

- name: Specify IR device name
  lineinfile:
    dest: /etc/sysconfig/lirc
    line: LIRCD_DEVICE="{{ ir_device.device }}"
    regexp: "^LIRCD_DEVICE=.*"

- name: Specify IR kernel module name
  lineinfile:
    dest: /etc/sysconfig/lirc
    line: LIRCD_MODULE="{{ ir_device.module }}"
    regexp: "^LIRCD_MODULE=.*"

- name: Enable lirc
  service:
    name: lirc
    enabled: yes
