---
# kernel.yml
#
# Grab and install desired kernel.version from Ubuntu PPA site

- name: Check current kernel version
  command: uname -r
  register: kernel_version
  changed_when: False

- name: Updated kernel headers (all)
  apt:
    deb: "{{ kernel.origin }}/v{{ kernel.version | regex_replace('\\.0$','')
      }}/linux-headers-{{ kernel.version }}-{{ kernel.short_ver
      }}_{{ kernel.long_ver }}_all.deb"
  when: kernel_version.stdout != '%s-%s-generic' % (kernel.version, kernel.short_ver)

- name: Updated generic kernel headers (amd64)
  apt:
    deb: "{{ kernel.origin }}/v{{ kernel.version | regex_replace('\\.0$','')
      }}/linux-headers-{{ kernel.version }}-{{ kernel.short_ver
      }}-generic_{{ kernel.long_ver }}_amd64.deb"
  when: kernel_version.stdout != '%s-%s-generic' % (kernel.version, kernel.short_ver)

- name: Updated kernel image (amd64)
  apt:
    deb: "{{ kernel.origin }}/v{{ kernel.version | regex_replace('\\.0$','')
      }}/linux-image-{{ kernel.version }}-{{ kernel.short_ver
      }}-generic_{{ kernel.long_ver }}_amd64.deb"
  when: kernel_version.stdout != '%s-%s-generic' % (kernel.version, kernel.short_ver)
