apiVersion: v2
name: samba
description: samba file server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://gitlab.com/samba-team/samba
type: application
version: 0.1.4
appVersion: "4.15.7-r0"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
