version: "3"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/samba:latest
    network_mode: host
    restart: always
    environment:
      LOG_LEVEL: 3
      NETBIOS_NAME: ${SAMBA_NETBIOS_NAME:-samba}
      SERVER_STRING: ${SAMBA_SERVER_STRING:-Samba Server}
      TZ: ${TZ:-UTC}
      WORKGROUP: ${SAMBA_WORKGROUP:-WORKGROUP}
    volumes:
    - ${ADMIN_PATH}/samba/etc:/etc/samba/conf.d:ro
    - ${SHARE_PATH}/samba/var/lib:/var/lib/samba
    - log:/var/log/samba
    # Add your mounts here
    ports:
    - 137-138:137-138/udp
    - 139:139
    - 445:445

volumes:
  log:
