version: "3"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/spamassassin:latest
    environment:
      EXTRA_OPTIONS: --nouser-config --sql-config
    ports:
    - 783:783
    volumes:
    - /var/lib/docker/share/spamd/etc/local.cf:/etc/mail/spamassassin/local.cf:ro
    - home:/var/lib/spamassassin
    - logs:/var/log
    deploy:
      mode: global
      placement:
        constraints:
        - node.labels.swarm-sync-member == true

networks:
  default:
    external:
      name: app_net
volumes:
  home:
  logs:
