---
# set up a fileserver

# Usage:
#
#  ansible-playbook fileserver-setup.yml

- hosts: fileservers
  become: True
  force_handlers: True
  roles:
  - { role: users, tags: users }
  - { role: network, tags: network }
  - { role: docker_node, tags: docker }
  - { role: monitoring_agent, tags: nagios }
  - { role: bind9, tags: bind9 }
  - { role: ntp, tags: ntp }
  - fileserver
  - { role: volumes, tags: volumes }
