version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/blacklist:${VERSION_BLACKLIST:-latest}
    environment:
      RBL_DOMAIN: ${RBL_DOMAIN:-blacklist.mydomain.com}
      NS_SERVERS: ${NS_SERVERS:-ns.mydomain.com}
      DB_HOST: ${DB_HOST:-db}
    ports:
    - ${PORT_BLACKLIST:-53}:53/udp
    volumes:
    - data:/var/lib/rbldns
    secrets:
    - mysql-blacklist-user

networks:
  default:
    external:
      name: app_net
volumes:
  data:
secrets:
  mysql-blacklist-user:
    external: true
