version: "3.1"

services:
  app:
    image: instantlinux/blacklist:latest
    environment:
      RBL_DOMAIN: blacklist.ci.net
      NS_SERVERS: node1.ci.net node2.ci.net node3.ci.net
      DB_HOST: xdb00
    ports:
    - 53:53/udp
    volumes:
    - data:/var/lib/rbldns
    secrets:
    - mysql-blacklist-user

networks:
  default:
    external:
      name: app_net
volumes:
  data:
secrets:
  mysql-blacklist-user:
    external: true
