version: "3.1"
# Synchronize two swarm nodes
#  Note that the stack has to be redeployed any time a new volume
#  mount is added underneath the top-level share

services:

  primary:
    image: ${REGISTRY_URI:-instantlinux}/swarm-sync:latest
    environment:
      SYNC_INTERVAL: "2"
      TZ: US/Pacific
    volumes:
    - logs:/var/log/unison
    - syncarchive:/root/.unison
    - ${SHARE_PATH}:/var/swarm-sync
    secrets:
    - swarm-sync_sshkey
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary
    depends_on:
    - peer

  peer:
    image: ${REGISTRY_URI:-instantlinux}/swarm-sync:latest
    environment:
      SYNC_ROLE: peer
    env_file:
    - ../../.docker/swarm-sync.pub.env
    volumes:
    - etcssh:/etc/ssh
    - syncarchive:/root/.unison
    - ${SHARE_PATH}:/var/swarm-sync
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == peer

volumes:
  etcssh:
  logs:
  syncarchive:
secrets:
  swarm-sync_sshkey:
    external: true
