apiVersion: v2
name: nextcloud
description: Nextcloud file-sharing and application server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
type: application
version: 0.1.6
appVersion: "32.0.5"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
