apiVersion: v2
name: etcd
description: Distributed kv-store - for VERSION 2 API, not 3
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/etcd-io/etcd
type: application
version: 0.1.1
appVersion: "v3.5.1"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
