apiVersion: v2
name: git-pull
description: Keep a directory path in sync with periodic git pull
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
type: application
version: 0.1.4
appVersion: "2.38.1-r0"
dependencies:
- name: chartlib
  version: 0.1.8
  # repository: https://instantlinux.github.io/docker-tools
  repository: file://../chartlib
