apiVersion: v2
name: data-sync
description: git backup
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
type: application
version: 0.1.13
appVersion: "2.53.5-4.14.2-r1"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
