version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/squirrelmail:${VERSION_SQUIRRELMAIL:-latest}
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME_ADDR: rbaddr
      DOMAIN: pioneer.ci.net
      IMAP_SERVER: swarm00.ci.net
      MESSAGE_MOTD: Remote WebMail Access \&nbsp;\&nbsp; pioneer.ci.net  
      ORGANIZATION: Community Internet
      SMTP_PORT: 25
      SMTP_SMARTHOST: smtp.ci.net
    ports:
    - ${PORT_SQUIRRELMAIL:-8080}:80
    volumes:
    - ${SHARE_PATH}/squirrelmail/attach:/var/local/squirrelmail/attach
    - ${SHARE_PATH}/squirrelmail/data:/var/local/squirrelmail/data
    - logs:/var/log/apache2
    secrets:
    - squirrelmail-db-password
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

volumes:
  logs:
networks:
  default:
    external:
      name: app_net
secrets:
  squirrelmail-db-password:
    external: true
