apiVersion: v2
name: openldap
description: openldap
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://git.openldap.org/openldap/openldap
type: application
version: 0.1.3
appVersion: "2.6.4-r3"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
