version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/weewx:latest
    restart: always
    environment:
      ALTITUDE: 100, foot
      DB_HOST: ${DB_HOST:-db00}
      DB_USER: wx
      LATITUDE: ${WX_LATITUDE:-38.898}
      LONGITUDE: ${WX_LONGITUDE:--77.037}
      LOCATION: ${WX_LOCATION:-Local Weather Station}
      RAIN_YEAR_START: ${WX_RAIN_YEAR_START:-7}
      RSYNC_DEST: ${WX_RSYNC_DEST:-/usr/share/nginx/html}
      RSYNC_HOST: ${WX_RSYNC_HOST:-web01}
      RSYNC_PORT: ${PORT_WX_SSH:-22}
      SKIN: WeeGreen
      STATION_ID: ${WX_STATION_ID}
      STATION_URL: ${WX_STATION_URL:- }
      SYSLOG_DEST: "@@${RSYSLOGD_HOST:-syslog}:${PORT_RSYSLOGD:-514}"
      TZ: ${TZ:-UTC}
      TZ_CODE: 4
      XTIDE_LOCATION: San Francisco
    tmpfs:
    - /var/www/weewx
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: bridge
    secrets:
    - weewx-db-password
    - weewx-rsync-sshkey
    - weewx-wunderground-apikey
    - weewx-wunderground-password

secrets:
  weewx-db-password:
    file: /var/adm/secrets/weewx-db-password
  weewx-rsync-sshkey:
    file: /var/adm/secrets/weewx-rsync-sshkey
  weewx-wunderground-apikey:
    file: /var/adm/secrets/weewx-wunderground-apikey
  weewx-wunderground-password:
    file: /var/adm/secrets/weewx-wunderground-password
