apiVersion: v2
name: jira
description: Jira issue and project tracking
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://hub.docker.com/r/atlassian/jira-core
type: application
version: 0.1.0
appVersion: "8.13.4"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
