apiVersion: v2
name: dovecot
description: Dovecot imapd server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/vdukhovni/dovecot
type: application
version: 0.1.8
appVersion: "2.3.21-r17"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
- name: data-sync
  version: 0.1.3
  repository: https://instantlinux.github.io/docker-tools
